# .cnb.yml
$:
  vscode:
    - docker:
        # 指定开发环境镜像，可以是任意可访问的镜像。
        # 如果 image 指定的镜像中已安装 code-server 代码服务，将使用单容器模式启动开发环境
        # 如果 image 指定的镜像中未安装 code-server 代码服务，将使用双容器模式启动开发环境
        # 如下镜像为 CNB 默认开发环境镜像，已安装代码服务，将使用单容器模式启动开发环境
        # 可按需替换为其他镜像
        build: 
          dockerfile: .ide/Dockerfile
        #   by:
        #     - .ide/vscode-server.sh
        # image: docker.cnb.cool/nrzhangsan/solana-simple/env:latest
      runner:
        cpus: 8
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: CNB_VSCODE_PROXY_URI
          script:
            - echo "# endpoints" >> CNB_VSCODE_PROXY_URI
            - echo "$CNB_VSCODE_PROXY_URI" >> CNB_VSCODE_PROXY_URI
        - name: docker-openssh-servers
          script:
            - docker run -d --name ssh-server -p 1022:2222 -e SUDO_ACCESS=true -e USER_NAME=admin -e PASSWORD_ACCESS=true -e USER_PASSWORD=123456 lscr.io/linuxserver/openssh-server
