name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Moon env
        run: |
          apt-get update && apt-get install -y gcc libssl-dev
          curl -fsSL https://cli.moonbitlang.cn/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Moon test
        run: |
          echo moon test
          moon test --enable-coverage
          moon coverage report -f summary

          # # ffi test 存在问题，先注释
          # echo moon test native
          # moon test --target native --enable-coverage
          # moon coverage --target native report -f summary

      - name: Run ssh-server scripts, start ssh server
        run: |
          set -e

          echo "Running ssh-server scripts..."

          cd scripts/ssh-server/
          chmod +x *.sh

          for f in *.sh; do
            echo "==> Running $f"
            bash "$f"
          done

      - name: Run cmd/password sequentially, run moon connect to ssh server
        run: |
          set -e

          echo "Running cmd/password run.sh..."
          export workspace=$(pwd)

          cd cmd/password
          chmod +x run.sh
          bash run.sh

      - name: Run cmd/key sequentially, run moon connect to ssh server
        run: |
          set -e

          echo "Running cmd/key run_xx.sh..."
          export workspace=$(pwd)

          cd cmd/key
          chmod +x *.sh

          for f in *.sh; do
            echo "==> Running $f"
            bash "$f"
          done
      
      - name: Run cmd/sftp sequentially, run moon connect to ssh server
        run: |
          set -e

          echo "Running cmd/sftp run.sh..."
          export workspace=$(pwd)

          cd cmd/sftp
          chmod +x run.sh
          bash run.sh
