name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Moon env
        run: |
          apt-get update && apt-get install -y gcc libssl-dev
          curl -fsSL https://cli.moonbitlang.cn/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Moon test
        run: |
          moon test --enable-coverage
          moon coverage report -f summary

      - name: Run ssh-server scripts, start ssh server
        run: |
          set -e

          echo "Running ssh-server scripts..."

          cd scripts/ssh-server/
          chmod +x *.sh
          
          for f in *.sh; do
            echo "==> Running $f"
            bash "$f"
          done

          cd ../..

      - name: Run cmd modules sequentially, run moon connect to ssh server
        run: |
          set -e

          pwd
          echo "Running cmd run.sh..."

          for d in cmd/*; do
            if [ -f "$d/run.sh" ]; then
              echo "==> Running $d/run.sh"
              pwd
              echo $d
              cd $d
              chmod +x run.sh"
              bash "run.sh"
              cd ..
            fi
          done
          pwd
          cd ..
          pwd